In [3]:
import numpy as np

In [12]:
#U=[]
#U[1]=np.array([[-0.3, 1.0, 1.2], [1.6, -1.0, -1.1]])
#U[2]=np.array([[1.0, 1.0, -1.0], [0.7, 0.5, 1.0]])
#U[3]=np.array([[0.5, -0.8, 1.0], [-0.1, 0.3, 0.4]])
#U[4]=np.array([[1.0, 0.1, -0.2], [-0.2, 1.3, -0.4]])

# 만들고 싶은 배열에 원소 없는 상태에서 바로 인덱스로 접근해서 값 넣을 수는 없음!!
# cf. np.array : ndarray형. 이건 벡터 연산(덧셈 등)이 가능

In [22]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C_Y = np.concatenate((A, B), axis = 0)
print(C_Y)
C_X = np.concatenate((A, B), axis = 1)
print(C_X)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [23]:
# 리스트 7-1-(4)
# 시그모이드 함수 ------------------------
def Sigmoid(x):
    y = 1 / (1 + np.exp(-x))
    return y


# 네트워크 ------------------------
def FNN(wv, M, K, x):
    N, D = x.shape # 입력 차원
    w = wv[:M * (D + 1)] # 중간층 뉴런의 가중치
    w = w.reshape(M, (D + 1))
    v = wv[M * (D + 1):] # 출력층 뉴런의 가중치
    v = v.reshape((K, M + 1))
    b = np.zeros((N, M + 1)) # 중간층 뉴런의 입력 총합
    z = np.zeros((N, M + 1)) # 중간층 뉴런의 출력
    a = np.zeros((N, K)) # 출력층 뉴런의 입력 총합
    y = np.zeros((N, K)) # 출력층 뉴런의 출력
    for n in range(N):
        # 중간층의 계산
        for m in range(M):
            b[n, m] = np.dot(w[m, :], np.r_[x[n, :], 1]) # (A)
            z[n, m] = Sigmoid(b[n, m])
        # 출력층의 계산
        z[n, M] = 1 # 더미 뉴런
        wkz = 0
        for k in range(K):
            a[n, k] = np.dot(v[k, :], z[n, :])
            wkz = wkz + np.exp(a[n, k])
        for k in range(K):
            y[n, k] = np.exp(a[n, k]) / wkz
    return y, a, z, b

# test ---
WV = np.ones(15) # Mx(D+1)+ Kx(M+1) = 2x3+3x3 = 15, 모든 가중치를 1로 초기화
M = 2
K = 3
FNN(WV, M, K, X_train[:2, :])

NameError: name 'X_train' is not defined

In [22]:
U=[np.array([[-0.3, 1.0, 1.2], [1.6, -1.0, -1.1]]),
   np.array([[1.0, 1.0, -1.0], [0.7, 0.5, 1.0]]),
   np.array([[0.5, -0.8, 0.9], [-0.1, 0.3, 0.4]]),
   np.array([[1.0, 0.1, -0.2], [-0.2, 1.3, -0.4]])
  ]

In [23]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [24]:
def ReLU(x):
    return max(0,x)

In [25]:
x = np.array([[1,1,0]])
x = np.transpose(x)
print(x)

[[1]
 [1]
 [0]]


In [26]:
print(U[0].dot(x))
print(ReLU(0.7))
print(ReLU(0.6))

[[0.7]
 [0.6]]
0.7
0.6


In [27]:
x = np.array([[1, 0.7, 0.6]])
x = np.transpose(x)
print(x)

[[1. ]
 [0.7]
 [0.6]]


In [28]:
print(U[1].dot(x))

[[1.1 ]
 [1.65]]


In [29]:
print(ReLU(1.1))
print(ReLU(1.65))

1.1
1.65


In [30]:
x = np.array([[1, 1.1, 1.65]])
x = np.transpose(x)
print(x)

[[1.  ]
 [1.1 ]
 [1.65]]


In [31]:
print(U[2].dot(x))

[[1.105]
 [0.89 ]]


In [32]:
print(ReLU(1.105))
print(ReLU(0.89))

1.105
0.89


In [33]:
x = np.array([[1, 1.105, 0.89]])
x = np.transpose(x)
print(x)

[[1.   ]
 [1.105]
 [0.89 ]]


In [34]:
print(U[3].dot(x))

[[0.9325]
 [0.8805]]


In [35]:
print(ReLU(0.9325))
print(ReLU(0.8805))

0.9325
0.8805


In [7]:
def convolution2d(image, kernel):
    m, n = kernel.shape
    if (m == n):
        y, x = image.shape
        y = y - m + 1
        x = x - m + 1
        new_image = np.zeros((y,x))
        for i in range(y):
            for j in range(x):
                new_image[i][j] = np.sum(image[i:i+m, j:j+m]*kernel)
    return new_image

In [20]:
R = np.array([[0,0,0,0,0], [0,1,1,1,0], [0,0,0,3,0], [0,2,0,0,0], [0,0,0,0,0]])  # print(R.shape) ==> (5,5)
G = np.array([[0,0,0,0,0], [0,2,2,2,0], [0,0,0,1,0], [3,0,0,1,0], [0,1,0,0,0]])
B = np.array([[0,0,0,0,0], [0,0,3,0,0], [0,1,0,1,0], [0,1,0,0,0], [0,0,0,0,0]])

c1 = np.array([[0,0,0], [0,0,1], [0,1,0]])
c2 = np.array([[0,2,0], [0,2,0], [0,2,0]])
c3 = np.array([[1,0,0], [0,2,0], [0,0,1]])

print(convolution2d(R, c1))
# convRGB = convolution2d(R,)

[[1. 1. 3.]
 [2. 3. 0.]
 [0. 0. 0.]]
